In [1]:
import pandas as pd
df = pd.read_csv("clean_data.csv")
df

,Unnamed: 0,id,title,genres,original_language,overview,popularity,production_companies,release_date,budget,...,runtime,status,tagline,vote_average,vote_count,credits,keywords,poster_path,backdrop_path,recommendations
0,152,785521,Battle: Freestyle,Romance-Drama,no,Amalie and Mikael lead their street dance team...,238.540,Friland Produksjon AS,2022-04-01,0.0,...,88.0,Released,NaN,5.1,30.0,Lisa Teige-Fabian Svegaard Tapia-Ellen Dorrit ...,paris france-based on novel or book-norway-dan...,/6D6QumiHEhnpZG12Ibjy2BxA6n4.jpg,/8WpRRiz3qQqzBiifCTm1dW0b6bs.jpg,818750-790525-800407-739993-946726-682344-9532...
1,163,949218,S.O.S. Mamis: La película,Comedy,es,Trini's daughter is sad that her best friend i...,230.012,Tiki Pictures-BH5-Elefantec Global,2022-03-18,0.0,...,105.0,Released,NaN,5.9,9.0,Paz Bascuñan-Loreto Aravena-María Elena Swett-...,based on web series,/dubFxWUiXW4QzOygVsChYYIuzfx.jpg,/9y7gXxImkZkqniB96TfryYJG3mh.jpg,NaN
2,164,928769,AI Love You,Comedy-Romance-Science Fiction,th,A modern love story set in the near future whe...,226.559,Deyi Production-Blue River Films,2022-02-15,0.0,...,95.0,Released,NaN,5.4,25.0,Mario Maurer-Pimchanok Leuwisetpaiboon-Michael...,NaN,/sBiJOvHCSWORnFpc4yItflIkdTi.jpg,/AfWtIzrdB0HMQ0Swequza4Jo1Kh.jpg,615904-929472-890656-892153-800510-818647-6327...
3,180,785521,Battle: Freestyle,Romance-Drama,no,Amalie and Mikael lead their street dance team...,210.928,Friland Produksjon AS,2022-04-01,0.0,...,88.0,Released,NaN,5.1,30.0,Lisa Teige-Fabian Svegaard Tapia-Ellen Dorrit ...,paris france-based on novel or book-norway-dan...,/6D6QumiHEhnpZG12Ibjy2BxA6n4.jpg,/8WpRRiz3qQqzBiifCTm1dW0b6bs.jpg,818750-790525-800407-739993-946726-682344-9532...
4,192,831223,Gone Mom: The Disappearance of Jennifer Dulos,TV Movie-Thriller-Crime,en,Jennifer Dulos the wealthy Connecticut mother-...,201.142,Lighthouse Pictures,2021-06-05,0.0,...,88.0,Released,NaN,7.7,151.0,Annabeth Gish-Warren Christie-Laura Harris-Ken...,NaN,/mzTNGnLG6LTHmrqrY0IADHDuyOJ.jpg,/kJ2srEZSlmGfAqLKGVMPhBDdr1G.jpg,425909-754067-645886-661004-460458-831827-5850...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147388,722723,772891,408,Comedy-Crime,ca,Carles Pau and Dante meet at the funeral of th...,0.600,NaN,2019-06-08,0.0,...,0.0,Released,NaN,0.0,0.0,Carlos Llecha-Rodo Gener-Toni Pons-Toni Villal...,NaN,/kOCr3OrZyXmrVeEfGcGp2t6F2Mq.jpg,/9dGfeASrddwN1vyYWeGB7WQcr1I.jpg,NaN
147389,722734,869220,Quicksand,NaN,en,An elderly gentleman attempts to retrieve forg...,0.600,NaN,NaN,0.0,...,8.0,Released,NaN,0.0,0.0,Roy Oppenheim-Walter Oppenheim,NaN,NaN,NaN,NaN
147390,722738,548760,Wolves of the North,Adventure-Action,en,The adventures of fur trappers in the Pacific ...,0.600,Universal Pictures,1924-09-21,0.0,...,0.0,Released,NaN,0.0,0.0,William Duncan-Edith Johnson-Joseph W. Girard-...,fur trapping,/xQwdOJVQpjtvc50Ys2HYFO89BYi.jpg,/nQBmYGkfC2lulniQxB0yZievYtd.jpg,NaN
147391,722740,702248,Weeping Shriner,NaN,en,A grieving emotionally repressed lounge pianis...,0.600,NaN,1999-08-30,0.0,...,0.0,Released,NaN,0.0,0.0,NaN,NaN,/64j2qDJodQ8du8AJuls3D4WTc6W.jpg,NaN,NaN
147392,722744,912284,Smile,Animation,en,GroM wakes up one morning to find that his mou...,0.600,Menado,2021-07-30,0.0,...,7.0,Released,NaN,0.0,0.0,Anders Wilhelmsson-Emma-Helena Berglund-Eirik ...,NaN,/arkZvwlLa4v0QzJZEs8ycnC3dKJ.jpg,NaN,NaN

In [7]:
df_oldest= df
df_newest = df

In [8]:
df_oldest['release_date'] = pd.to_datetime(df.release_date, infer_datetime_format = True)
df_oldest.sort_values(by = 'release_date', ascending = True, inplace = True)
df_oldest[['title', 'release_date']].head(25)

                                              title release_date
115064                                 The Aquarium   1878-05-07
35776                                      The Kiss   1882-06-01
114818                     Woman Walking Downstairs   1887-01-01
32502                              Hyde Park Corner   1889-11-23
27686                                  Je Vous Aime   1891-01-01
131574                   Monkey and Another, Boxing   1891-01-01
27134                                      The Wave   1891-11-15
130231                                    Wrestling   1892-01-01
48274                                        Boxing   1892-01-01
137784                                      Rabbits   1893-02-01
51006                             Athlete with Wand   1894-02-01
70864                                Highland Dance   1894-04-01
90637                                  Buffalo Bill   1894-06-17
26718                                 Buffalo Dance   1894-09-23
27445                                  Hadj Cheriff   1894-10-05
80526                                 Lasso Thrower   1894-10-06
23803                               Bucking Broncho   1894-10-16
15669                                  Annie Oakley   1894-11-01
35495                       Imperial Japanese Dance   1894-11-05
49476   Corbett and Courtney Before the Kinetograph   1894-11-17
130129                                        Dance   1894-12-01
34628                              Déjeuner du Chat   1895-01-01
45287                                    Photograph   1895-01-01
16899                        Transformation by Hats   1895-01-01
22574                           Le maréchal-ferrant   1895-01-01

In [9]:
df_newest['release_date'] = pd.to_datetime(df.release_date, infer_datetime_format = True)
df_newest.sort_values(by = 'release_date', ascending = False, inplace = True)
df_newest[['title', 'release_date']].head(25)

                         title release_date
50396            The Wild Ones   2025-06-13
296             Fantastic Four   2025-02-12
51801              Son Göktürk   2025-01-01
8269                    Wicked   2024-12-25
290                      Blade   2024-09-04
1989                  Garfield   2024-05-24
19140                  Fighter   2024-01-25
4649                   Distant   2024-01-19
29702               Metro 2033   2024-01-01
18691               Metro 2033   2024-01-01
3180              Attraction 3   2024-01-01
122569                   Guilt   2023-12-31
21643                The Field   2023-12-31
71765                12 Chairs   2023-12-31
60495                Lifelines   2023-12-31
9696                   Anomaly   2023-12-31
41421              Before Dawn   2023-12-31
51466                   Escape   2023-12-31
35245                Ballerina   2023-12-31
65104    Guest from the Future   2023-12-28
14591   Bade Miyan Chote Miyan   2023-12-25
759           The Color Purple   2023-12-20
17327               Aashiqui 3   2023-11-10
2241                The Killer   2023-11-10
68204               Inevitable   2023-11-03